book/urls.py
from django.urls import path
from . import views

# app_name='book'

urlpatterns=[
    # path('books/', views.BookListView.as_view(), name='book_list'),
    path('books/',views.book_list,name='book_list'),
    path('books/tag/<slug:tag_slug>',views.book_list,name='book_list_by_tag'),
    # path('books/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('books/<int:book_id>/', views.book_detail, name='book_detail'),

    


]

myadmin/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('<int:pk>/delete',views.DeleteGenericView.as_view(), name='delete'),
    path('create/',views.CreateGenericView.as_view(),name='create_product'),
    path('edit/<int:pk>',views.EditGenericView.as_view(),name='edit'),
    path('all_users/', views.All_users.as_view(), name='all_users'),
    # path('all/',views.get_all,name='get_all')
    path('users/<int:pk>/', views.UsersDetailView.as_view(), name='user_details'),
    path('display/', views.Display.as_view(), name='display'),
    path('search/', views.search_user, name='search_user'),
    path('allborrowed/',views.AllBorrowedBooks.as_view(),name='allborrowed')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('students/',include('students.urls')),
    path('myadmin/',include('myadmin.urls')),
    path('book/',include('book.urls')),

    
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
from taggit.managers import TaggableManager
from django.urls import reverse



def in_three_days():
    return timezone.now() + timedelta(days=3)

class Books(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100,null=True)
    is_available = models.BooleanField(default=True)
    image=models.ImageField(upload_to='book/images',null=True)
    tags=TaggableManager()
    
    def __str__(self) :
        return self.title
    



class BorrowedBook(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='hh')
    borrow_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateTimeField(default=in_three_days,null=True, blank=True)
    STATUS_CHOICES = (
        ('B', 'Borrowed'),
        ('R', 'Returned'),
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='B')
    
    

myadmin/models.py
from django.db import models

# Create your models here.

myadmin/forms.py
from django import forms
from book.models import Books




class CreateForm(forms.ModelForm):
    
    class Meta:
        model=Books
        fields='__all__'
        

myadmin/views.py
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from book.models import Books
from django.views.generic import CreateView,ListView,DetailView
from .forms import CreateForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from book.models import BorrowedBook
from django.contrib.auth.mixins import LoginRequiredMixin


    
    
    
class DeleteGenericView(DeleteView):
    model=Books
    template_name='myadmin/delete.html'
    
    success_url=reverse_lazy('book_list')
    


class CreateGenericView(CreateView):
    form_class=CreateForm
    template_name='myadmin/create_book.html'
    success_url=reverse_lazy('book_list')
    
    
    
    
class EditGenericView(LoginRequiredMixin,UpdateView):
    model=Books
    form_class=CreateForm
    template_name='myadmin/edit_book.html'
    success_url=reverse_lazy('book_list')
    

class All_users(ListView):
    model=User
    
    template_name='myadmin/all_users.html'
    queryset=User.objects.all()


# def get_all(request):
#     User=get_user_model()
#     users=User.objects.all()
#     return render(request,'admin/all_users.html',{'users':users})


class UsersDetailView(DetailView):
    model=User
    template_name = 'myadmin/user_details.html'
    
    
class Display(ListView):
    model=Books
    template_name='myadmin/display.html'
    queryset=Books.objects.all()
    
    
    
# def get_user(request,user_id):
#     try:
#         student=User.objects.get(id=user_id)
#         return render(request,'myadmin/get_user.html',{'student':student})
#     except:
#         return HttpResponse("does not exist")
    
    
    
    
# def get_user(request):
#     if request.method=='Post':
#         searched=request.POST['searched']
#         students=User.objects.get(id=searched)
#         return render(request,'myadmin/get_user.html',{'searched':searched,'students':students})
    
#     return render(request,'myadmin/get_user.html')



def search_user(request):
    if request.method == 'POST':
        user_id = request.POST.get('search')
        try:
            user = User.objects.get(id=user_id)
            return redirect('user_details', pk=user.id)
        except User.DoesNotExist:
            error_message = "User not found."
            return render(request, 'error.html', {'error_message': error_message})
    else:
        return redirect('book_list')






class AllBorrowedBooks(ListView):
    model=BorrowedBook
    template_name='myadmin/borrowed_book_list.html'
    queryset=BorrowedBook.objects.all()
        
        

myadmin/templates/myadmin/all_users.html
<!DOCTYPE html>
<html>

<head>
  <style>
    /* Global styles */
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    /* Header styles */
    .navbar {
      background-color: #333;
      color: #fff;
      padding: 10px;
    }

    .navbar-header {
      display: inline-block;
    }

    .navbar-brand {
      color: #fff;
      font-size: 24px;
      font-weight: bold;
      text-decoration: none;
      margin-right: 20px;
    }

    .navbar-nav {
      display: inline-block;
      list-style: none;
      margin: 0;
      padding: 0;
    }

    .navbar-nav li {
      display: inline-block;
      margin-right: 10px;
    }

    .navbar-nav li a {
      color: #fff;
      text-decoration: none;
    }

    .navbar-nav li.active a {
      font-weight: bold;
    }

    .navbar-right {
      float: right;
    }

    .navbar-right li {
      display: inline-block;
      margin-left: 10px;
    }

    .navbar-right li a {
      color: #fff;
      text-decoration: none;
    }

    .glyphicon {
      margin-right: 5px;
    }

    /* User list styles */
    .user-list {
      margin-top: 20px;
      padding: 0;
      list-style: none;
    }

    .user-list-item {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
    }

    .user-list-item .username {
      font-weight: bold;
      margin-right: 10px;
    }

    .user-list-item button {
      background-color: #333;
      color: #fff;
      border: none;
      padding: 5px 10px;
      border-radius: 3px;
      cursor: pointer;
      text-decoration: none;
    }

    .user-list-item button a {
      color: #fff;
      text-decoration: none;
    }
  </style>
</head>

<body>
  <nav class="navbar">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'profile' %}">Profile</a>
    </div>
    <ul class="navbar-nav">
      <li class="active"><a href="/book/books/">Books</a></li>
      <li><a href="">About Us</a></li>
      <li><a href="">Contact Us</a></li>
    </ul>
    <ul class="navbar-nav navbar-right">
      {% if user.is_authenticated %}
      Welcome {{ user.username }}
      <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
      {% else %}
      <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
      {% endif %}
    </ul>
  </nav>
  
  <ul class="user-list">
    {% for object in object_list %}
    <li class="user-list-item">
      <span class="username">{{ object.username }}</span>
      <button type="submit"><a href="{% url 'user_details' pk=object.id %}">Details</a></button>
    </li>
    {% endfor %}
  </ul>
</body>

</html>

myadmin/templates/myadmin/borrowed_book_list.html
{% extends 'base.html'  %}
{% block content %}


<!DOCTYPE html>
<html>
<head>
  <title>Borrowed Book List</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
  <style>
    .borrowed-book-list {
      border: 1px solid #ccc;
      padding: 20px;
      max-width: 400px;
      margin: 0 auto;
      text-align: center;
      font-family: Arial, sans-serif;
    }
    
    .borrowed-book-list h1 {
      font-size: 24px;
      margin-bottom: 10px;
    }
    
    .borrowed-book-list ul {
      list-style-type: none;
      padding: 0;
      margin-top: 10px;
    }
    
    .borrowed-book-list li {
      font-size: 18px;
      margin-bottom: 5px;
    }
    
    .borrowed-book-list p {
      font-size: 18px;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
  <div class="borrowed-book-list">
    <h1>Borrowed Book List</h1>
    
      <ul>
        {% for object in object_list %}
          <li>Book title :{{ object.book.title }}</li>
          <li>Return date :{{ object.return_date }}</li>
          <li>User :{{ object.user }}</li>
          -----------------------------

        {% endfor %}
      </ul>
  </div>
</body>
</html>
{% endblock content%}

myadmin/templates/myadmin/create_book.html
{% extends 'base.html'%}
{% block content%}

<!DOCTYPE html>
<html>

<head>
  <title>Create Product</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
    }

    .container {
      margin-top: 50px;
      width: 400px;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
    }

    h1 {
      text-align: center;
      margin-bottom: 30px;
      color: #333;
    }

    form {
      margin-bottom: 20px;
    }

    .form-group {
      margin-bottom: 20px;
    }

    label {
      font-weight: bold;
      display: block;
      margin-bottom: 5px;
    }

    input[type="text"],
    input[type="file"] {
      width: 100%;
      padding: 8px;
      border: 1px solid #ccc;
      border-radius: 3px;
      font-size: 14px;
    }

    .btn-primary {
      width: 100%;
      background-color: #007bff;
      border: none;
      color: #fff;
      padding: 10px;
      border-radius: 3px;
      text-align: center;
      font-size: 16px;
      cursor: pointer;
    }

    .btn-primary:hover {
      background-color: #0056b3;
    }
  </style>
</head>

<body>
  <div class="container">
    <h1>Create Product</h1>
    <form method="Post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="id_title">Title:</label>
        {{ form.title }}
      </div>

      <div class="form-group">
        <label for="id_author">Author:</label>
        {{ form.author }}
      </div>
      <div class="form-group">
        <label for="id_author">Tags:</label>
        {{ form.tags }}
      </div>

      <div class="form-group">
        <label for="id_image">Image:</label>
        {{ form.image }}
      </div>

      <div class="form-group">
        <label for="id_is_available">Is Available:</label>
        {{ form.is_available }}
      </div>

      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>
</body>

</html>
{% endblock%}

myadmin/templates/myadmin/delete.html
{% extends 'base.html'  %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .bg-light {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            width: 400px;
            margin: 50px auto;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            text-align: center;
            margin-bottom: 20px;
        }

        p {
            font-size: 16px;
            margin-bottom: 20px;
            text-align: center;
        }

        .btn {
            display: inline-block;
            margin-right: 10px;
            padding: 10px 20px;
            border-radius: 5px;
            text-decoration: none;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .btn-danger {
            background-color: #dc3545;
            border: none;
        }

        .btn-dark {
            background-color: #343a40;
            border: none;
        }

        .btn:hover {
            background-color: #777;
        }
    </style>
</head>
<body>
    <div class="bg-light">
        <h1>Delete Book</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Are you sure you want to delete this post?</p>
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="#" class="btn btn-dark">Cancel</a>
        </form>
        
    </div>
</body>
</html>
{% endblock content%}

myadmin/templates/myadmin/display.html
{% extends 'base.html'%}
{% block content%}
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        .book-list {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .book-list-item {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 10px;
        }

        .book-thumbnail {
            width: 100px;
            margin-right: 20px;
        }

        .book-details {
            flex-grow: 1;
        }

        .book-title {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .book-author {
            color: #666;
            margin-bottom: 10px;
        }

        .book-user {
            color: #888;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Book List</h1>
        <ul class="book-list">
            {% for object in object_list %}
                <li class="book-list-item">
                    <img src="{{ object.image.url }}" alt="Book Thumbnail" class="book-thumbnail">
                    <div class="book-details">
                        <h2 class="book-title">Title : {{ object.title }}</h2>
                        <p class="book-author">Author: {{ object.author }}</p>
                        <p class="book-user">Is available: {{ object.is_available }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>
{% endblock content%}

myadmin/templates/myadmin/edit_book.html
{% extends 'base.html'%}
{% load static%}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>Edit Product</title>
<link rel="stylesheet" href="{% static 'myadmin/css/edit_book.css'%}">
</head>
<body>
  <div class="container">
    <h1>Edit Product</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'edit' pk=object.id %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_title">Title:</label>
        {{ form.title }}
      </div>

      <div class="form-group">
        <label for="id_author">Author:</label>
        {{ form.author }}
      </div>
      <div class="form-group">
        <label for="id_author">Tags:</label>
        {{ form.tags }}
      </div>

      <div class="form-group">
        <label for="id_image">Image:</label>
        {{ form.image }}
      </div>

      <div class="form-group">
        <label for="id_is_available">Is Available:</label>
        {{ form.is_available }}
      </div>
      <button type="submit">Update</button>
    </form>
  </div>
</body>
</html>
{% endblock content%}

myadmin/templates/myadmin/get_user.html
{% extends 'base.html'%}
{% block content%}
<!DOCTYPE html>
<html>
<head>
  <title>User Details</title>
  <link rel="stylesheet" href="path/to/custom.css">
  <style>
    body {
      font-family: Arial, sans-serif;
    }

    .container {
      max-width: 600px;
      margin: 50px auto;
      padding: 20px;
      background-color: #f8f9fa;
      border-radius: 5px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    h1 {
      text-align: center;
      margin-bottom: 30px;
    }

    .user-details {
      display: flex;
      align-items: center;
      margin-bottom: 20px;
    }

    .user-avatar {
      width: 50px;
      height: 50px;
      border-radius: 50%;
      margin-right: 10px;
    }

    .user-username {
      font-weight: bold;
      font-size: 18px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>User Details</h1>
    <div class="user-details">
      
      <span class="user-username">Username :{{ student.username }}</span>

    </div>
    <div class="user-details">
    <span class="user-username">First name :{{ student.first_name }}</span>
  </div>
  <div class="user-details">
    <span class="user-username">Last name :{{ student.last_name }}</span>
  </div>
  <div class="user-details">
    <span class="user-username">Email :{{ student.email }}</span>
  </div>
  </div>
</body>
</html>
{% endblock content%}

myadmin/templates/myadmin/user_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>.user-details {
        border: 1px solid #ccc;
        padding: 20px;
        max-width: 400px;
        margin: 0 auto;
        text-align: center;
        font-family: Arial, sans-serif;
      }
      
      .user-details h1 {
        font-size: 24px;
        margin-bottom: 10px;
      }
      
      .user-details .username, .user-details .email, .user-details .book-title {
        font-size: 18px;
        margin-bottom: 5px;
      }
      
      .user-details .book-title {
        font-style: italic;
      }</style>
</head>
<body>
    <div class="user-details">
        <h1>User Details</h1>
        
        <div class="username">Username :{{object.username}}</div>
        <div class="email">First name :{{object.first_name}}</div>    
        <div class="email">Last name :{{object.last_name}}</div>
        <div class="email">E-mail :{{object.email}}</div>

      </div>
</body>
</html>